### ISSUE TITLE
UpdateEvent ManyToMany Fields Not Implemented 

### ISSUE THREAD

**Issue by alderwhiteford** [GenerateNU/sac#317]
Throws the following error:

invalid field found for struct github.com/GenerateNU/sac/backend/src/models.UpdateEventRequestBody's field RSVP: define a valid foreign key for relations or implement the Valuer/Scanner interface
panic: reflect: call of reflect.Value.Field on string Value

goroutine 66 [running]:
reflect.Value.Field({0x102167960?, 0x1400083a600?, 0x380?}, 0x10296f300?)
        /Users/alderwhiteford/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.darwin-arm64/src/reflect/value.go:1284 +0xec
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func2({0x1021a7aa0?, 0x140003792f0?}, {0x1022883e0?, 0x1400083a600?, 0x0?})
        /Users/alderwhiteford/go/pkg/mod/gorm.io/gorm@v1.25.7/schema/field.go:462 +0xb8
gorm.io/gorm/callbacks.ConvertToAssignments(0x14000806380)
        /Users/alderwhiteford/go/pkg/mod/gorm.io/gorm@v1.25.7/callbacks/update.go:266 +0x6b0
gorm.io/gorm/callbacks.RegisterDefaultCallbacks.Update.func7(0x14000802570)
        /Users/alderwhiteford/go/pkg/mod/gorm.io/gorm@v1.25.7/callbacks/update.go:74 +0x154
gorm.io/gorm.(*processor).Execute(0x140000c7360, 0x140003cc840?)
        /Users/alderwhiteford/go/pkg/mod/gorm.io/gorm@v1.25.7/callbacks.go:130 +0x34c
gorm.io/gorm.(*DB).Updates(0x1022883e0?, {0x1022883e0, 0x1400083a600})
        /Users/alderwhiteford/go/pkg/mod/gorm.io/gorm@v1.25.7/finisher_api.go:411 +0x90
github.com/GenerateNU/sac/backend/src/transactions.UpdateEvent(_, {0x3c, 0xc6, 0x8c, 0x23, 0x4a, 0x73, 0x49, 0xc6, 0xa8, ...}, ...)
        /Users/alderwhiteford/Code/sac/backend/src/transactions/event.go:116 +0x164
github.com/GenerateNU/sac/backend/src/services.(*EventService).UpdateEvent(_, {_, _}, {{0x1400083e00f, 0x9}, {0x1400083e02b, 0x43}, {0x1400083e081, 0x1d}, {0x0, ...}, ...})
        /Users/alderwhiteford/Code/sac/backend/src/services/event.go:135 +0x178
github.com/GenerateNU/sac/backend/src/controllers.(*EventController).UpdateEvent(0x14000676600, 0x14000138008)
        /Users/alderwhiteford/Code/sac/backend/src/controllers/event.go:164 +0xb8
github.com/gofiber/fiber/v2.(*Ctx).Next(0x0?)
        /Users/alderwhiteford/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.1/ctx.go:1027 +0x48
github.com/GenerateNU/sac/backend/src/middleware.(*AuthMiddlewareService).ClubAuthorizeById(0x1400066a210, 0x14000138008)
        /Users/alderwhiteford/Code/sac/backend/src/middleware/club.go:16 +0x1f4
github.com/gofiber/fiber/v2.(*App).next(0x1400018a508, 0x14000138008)
        /Users/alderwhiteford/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.1/router.go:145 +0x188
github.com/gofiber/fiber/v2.(*Ctx).Next(0x14000138008?)
        /Users/alderwhiteford/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.1/ctx.go:1030 +0x5c
github.com/GenerateNU/sac/backend/src/middleware.(*AuthMiddlewareService).Authenticate(0x1400066a210, 0x14000138008)
        /Users/alderwhiteford/Code/sac/backend/src/middleware/auth.go:62 +0x180
github.com/gofiber/fiber/v2.(*App).next(0x1400018a508, 0x14000138008)
        /Users/alderwhiteford/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.1/router.go:145 +0x188
github.com/gofiber/fiber/v2.(*Ctx).Next(0x1400066a090?)
        /Users/alderwhiteford/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.1/ctx.go:1030 +0x5c
github.com/gofiber/fiber/v2/middleware/logger.New.func3(0x14000138008)
        /Users/alderwhiteford/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.1/middleware/logger/logger.go:119 +0x25c
github.com/gofiber/fiber/v2.(*Ctx).Next(0x14000038870?)
        /Users/alderwhiteford/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.1/ctx.go:1027 +0x48
github.com/GenerateNU/sac/backend/src/server.newFiberApp.New.func1(0x14000138008)
        /Users/alderwhiteford/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.1/middleware/requestid/requestid.go:31 +0xdc
github.com/gofiber/fiber/v2.(*Ctx).Next(0x140005b8938?)
        /Users/alderwhiteford/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.1/ctx.go:1027 +0x48
github.com/gofiber/fiber/v2/middleware/cors.New.func1(0x14000138008)
        /Users/alderwhiteford/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.1/middleware/cors/cors.go:185 +0x2c8
github.com/gofiber/fiber/v2.(*App).next(0x1400018a508, 0x14000138008)
        /Users/alderwhiteford/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.1/router.go:145 +0x188
github.com/gofiber/fiber/v2.(*App).handler(0x1400018a508, 0x1015766ac?)
        /Users/alderwhiteford/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.1/router.go:172 +0x74
github.com/valyala/fasthttp.(*Server).serveConn(0x14000596200, {0x1022c5a28, 0x1400012e3e0})
        /Users/alderwhiteford/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/server.go:2359 +0xb34
github.com/valyala/fasthttp.(*workerPool).workerFunc(0x140003d37c0, 0x14000804000)
        /Users/alderwhiteford/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/workerpool.go:224 +0x70
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        /Users/alderwhiteford/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/workerpool.go:196 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh in goroutine 1
        /Users/alderwhiteford/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/workerpool.go:195 +0x1e4
exit status 2

**Comment by alderwhiteford** [comment]
Fields removed already
